### ISSUE TITLE
Reanimated 2 error from OverlayProvider

### ISSUE THREAD

**Issue by anle1991** [GetStream/stream-chat-react-native#1135]
**Describe the bug**
My app hasn't made any change for chat functionality and I implemented the same as the example. It has been running until recently. I checked the docs for update but there isn't any. When I commented out OverlayProvider, things started to work normally without the chat functionality from Stream Chat.

**Dev environment info (please complete/provide the following information):**

- Package version (stream-chat-react-native/stream-chat-expo): "stream-chat-expo": "^3.10.2"
- react-native or expo version:  "expo": "^43.0.0"
- Device/Emulator (android/ios) and OS version: emulator iphone 13 Pro

**To Reproduce**

1. yarn start
2. install on ios

**Expected behavior**
App should load and chat tab should work.

**Additional context**
```
{
  "name": "loco-client",
  "version": "1.0.0",
  "private": true,
  "description": "Frontend for Lo Co",
  "author": "Lo Co team",
  "main": "node_modules/expo/AppEntry.js",
  "license": "MIT",
  "scripts": {
    "start": "yarn codegen && expo start",
    "dev": "yarn codegen && expo start --web",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "yarn codegen && next dev",
    "webexpo": "expo start --web",
    "eject": "expo eject",
    "test": "jest --watchAll",
    "build": "yarn codegen && next build",
    "codegen": "graphql-let",
    "build:web": "yarn codegen && expo build:web",
    "lint": "eslint './**/*.{js,ts,tsx}' --quiet --fix"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@apollo/client": "^3.3.6",
    "@apollo/react-hooks": "^4.0.0",
    "@expo-google-fonts/mali": "^0.1.0",
    "@expo-google-fonts/montserrat": "^0.1.0",
    "@expo/next-adapter": "^2.1.53",
    "@expo/vector-icons": "^12.0.0",
    "@gorhom/bottom-sheet": "^2",
    "@react-native-async-storage/async-storage": "~1.15.0",
    "@react-native-community/datetimepicker": "3.5.2",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-community/netinfo": "6.0.0",
    "@react-native-picker/picker": "2.1.0",
    "@react-navigation/bottom-tabs": "^5.11.1",
    "@react-navigation/core": "^5.15.3",
    "@react-navigation/material-top-tabs": "^5.3.15",
    "@react-navigation/native": "^5.8.9",
    "@react-navigation/stack": "^5.12.6",
    "@reduxjs/toolkit": "^1.6.2",
    "@types/lodash": "^4.14.168",
    "@types/react-native-snap-carousel": "^3.8.5",
    "@types/react-redux": "^7.1.20",
    "apollo-cache-inmemory": "^1.6.6",
    "apollo-client": "^2.6.10",
    "apollo-link": "^1.2.14",
    "apollo-link-context": "^1.0.20",
    "apollo-link-error": "^1.1.13",
    "apollo-link-rest": "^0.8.0-beta.0",
    "apollo-link-ws": "^1.0.20",
    "aws-sdk": "^2.822.0",
    "dayjs": "^1.10.6",
    "expo": "^43.0.0",
    "expo-analytics-amplitude": "~11.0.3",
    "expo-app-loading": "~1.2.1",
    "expo-apple-authentication": "~4.0.3",
    "expo-asset": "~8.4.3",
    "expo-blur": "~10.0.3",
    "expo-constants": "~12.1.3",
    "expo-crypto": "~10.0.3",
    "expo-document-picker": "~10.0.3",
    "expo-facebook": "~12.0.3",
    "expo-firebase-analytics": "~5.0.3",
    "expo-firebase-recaptcha": "~2.0.2",
    "expo-font": "~10.0.3",
    "expo-haptics": "~11.0.3",
    "expo-image-manipulator": "~10.1.2",
    "expo-image-picker": "~11.0.3",
    "expo-linking": "~2.4.2",
    "expo-localization": "~11.0.0",
    "expo-location": "~13.0.4",
    "expo-media-library": "~13.0.3",
    "expo-mixpanel-analytics": "^0.0.7",
    "expo-next-react-navigation": "^1.1.14",
    "expo-permissions": "~13.0.3",
    "expo-sharing": "~10.0.3",
    "expo-splash-screen": "~0.13.5",
    "expo-status-bar": "~1.1.0",
    "expo-web-browser": "~10.0.3",
    "firebase": "8.8.1",
    "graphql": "^15.4.0",
    "graphql-tag": "^2.11.0",
    "intl": "^1.2.5",
    "metro-react-native-babel-preset": "^0.66.2",
    "mixpanel-browser": "^2.40.0",
    "mixpanel-react-native": "^1.0.1",
    "next": "^10.0.4",
    "next-compose-plugins": "^2.2.1",
    "next-fonts": "^1.5.1",
    "next-images": "^1.6.2",
    "next-seo": "^4.17.0",
    "next-transpile-modules": "^6.0.0",
    "qs": "^6.9.4",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-firebase-hooks": "^3.0.4",
    "react-hook-form": "^7.9.0",
    "react-intl": "^5.10.9",
    "react-native": "https://github.com/expo/react-native/archive/sdk-43.tar.gz",
    "react-native-dotenv": "^3.3.0",
    "react-native-elements": "^3.4.2",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-google-places-autocomplete": "^2.1.2",
    "react-native-image-viewing": "^0.2.0",
    "react-native-in-app-notification": "^3.2.0",
    "react-native-logs": "^3.0.4",
    "react-native-maps": "0.28.1",
    "react-native-reanimated": "~2.2.0",
    "react-native-render-html": "^6.3.0",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "~3.8.0",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-svg": "12.1.1",
    "react-native-tab-view": "^2.16.0",
    "react-native-tailwindcss": "^1.1.11",
    "react-native-web": "0.17.1",
    "react-native-webview": "11.13.0",
    "react-navigation": "^4.4.4",
    "react-navigation-collapsible": "^5.10.2",
    "react-navigation-stack": "^2.10.2",
    "react-number-format": "^4.7.3",
    "react-redux": "^7.2.6",
    "stream-chat-expo": "^3.10.2",
    "subscriptions-transport-ws": "^0.9.18"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/helper-plugin-utils": "^7.10.4",
    "@babel/parser": "^7.12.11",
    "@babel/preset-react": "^7.12.10",
    "@babel/preset-typescript": "^7.12.7",
    "@babel/traverse": "^7.12.12",
    "@expo/webpack-config": "^0.16.2",
    "@graphql-codegen/cli": "^1.20.0",
    "@graphql-codegen/import-types-preset": "^1.18.4",
    "@graphql-codegen/plugin-helpers": "^1.18.2",
    "@graphql-codegen/typescript": "^1.19.0",
    "@graphql-codegen/typescript-operations": "^1.17.13",
    "@graphql-codegen/typescript-react-apollo": "^2.2.1",
    "@types/react": "~17.0.21",
    "@types/react-native": "~0.64.12",
    "@types/react-native-scrollable-tab-view": "^0.10.1",
    "@typescript-eslint/eslint-plugin": "^4.11.1",
    "@typescript-eslint/parser": "^4.11.1",
    "babel-loader": "^8.2.2",
    "do-sync": "^3.0.2",
    "dotenv": "^10.0.0",
    "eslint": "^7.16.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^3.3.0",
    "eslint-plugin-react": "^7.21.5",
    "graphql-let": "^0.18.4",
    "husky": "^4.3.8",
    "jest-expo": "^43.0.0",
    "lodash": "^4.17.21",
    "prettier": "^2.2.1",
    "typescript": "~4.3.5",
    "yaml-loader": "^0.6.0"
  },
  "husky": {
    "hooks": {
      "pre-commit": "yarn lint"
    }
  }
}

```

**Screenshots**
<img width="415" alt="Screen Shot 2022-02-10 at 9 49 39 PM" src="https://user-images.githubusercontent.com/6020782/153543624-6cea742b-38c6-4ddd-9e01-ac7d9265ca0b.png">

**Console log error**
```
Error: If you want to use Reanimated 2 then go through our installation steps https://docs.swmansion.com/react-native-reanimated/docs/installation

This error is located at:
    in OverlayProvider (created by AppFlow)
    in AppFlow (created by RootNavigator)
    in RootNavigator (created by Navigation)
    in PortalProvider (created by BottomSheetModalProviderWrapper)
    in BottomSheetModalProviderWrapper (created by Navigation)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainer (created by Navigation)
    in Navigation (created by App)
    in ThemeProvider (created by App)
    in Provider (created by App)
    in IntlProvider (created by App)
    in ApolloProvider (created by App)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by App)
    in App (created by ExpoRoot)
    in ExpoRoot
    in RCTView (created by View)
    in View (created by AppContainer)
    in DevAppContainer (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
at node_modules/expo/build/logs/LogSerialization.js:156:14 in _captureConsoleStackTrace
at node_modules/expo/build/logs/LogSerialization.js:41:26 in serializeLogDataAsync
- ... 9 more stack frames from framework internals
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:592:3)
    at tryReadSync (fs.js:366:20)
    at Object.readFileSync (fs.js:403:19)
    at UnableToResolveError.buildCodeFrameMessage (/Users/anle/Desktop/Projects/loco-client/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:347:17)
    at new UnableToResolveError (/Users/anle/Desktop/Projects/loco-client/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:333:35)
    at ModuleResolver.resolveDependency (/Users/anle/Desktop/Projects/loco-client/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:211:15)
    at DependencyGraph.resolveDependency (/Users/anle/Desktop/Projects/loco-client/node_modules/metro/src/node-haste/DependencyGraph.js:413:43)
    at /Users/anle/Desktop/Projects/loco-client/node_modules/metro/src/lib/transformHelpers.js:317:42
    at /Users/anle/Desktop/Projects/loco-client/node_modules/metro/src/Server.js:1471:14
    at Generator.next (<anonymous>)
```

**Comment by anle1991** [comment]
This is solved by upgrading expo to latest 44.
