### ISSUE TITLE
An error occurred while getting app settings: Error: timeout of 3000ms exceeded

### ISSUE THREAD

**Issue by RRaideRR** [GetStream/stream-chat-react-native#1537]
**Describe the bug**
I see occasionally on my local testing device, the simulator and in my production app the following error:
```
An error occurred while getting app settings: Error: timeout of 3000ms exceeded
at node_modules/stream-chat-react-native-core/src/components/Chat/hooks/useAppSettings.ts:24:10 in getAppSettings
at /Users/distiller/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:53:15 in tryCallOne
at /Users/distiller/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:139:26 in anonymous
- ... 8 more stack frames from framework internals
```

**Dev environment info (please complete/provide the following information):**

- stream-chat-expo: 4.7.3
- I use the expo version of stream-chat (Expo SDK 45)
- in Sentry, I can see that nearly every iOS version is affected

**To Reproduce**

That's the problem - I cannot reproduce it. It seems that the error appears occasionally after app start. I'm also unsure about the consequences of that error. Any help would be appreciated.

**Comment by RRaideRR** [comment]
Hi @santhoshvai.

two short queries regarding this: 

(1) Do I need to handle this in my app? e.g. try to reconnect or something like this? 

(2) Does the user experience some misbehavior when this error is thrown? e.g. he can't use the chat for that session?
