### ISSUE TITLE
react-native-quick-sqlite issue for offline support

### ISSUE THREAD

**Issue by billnbell** [GetStream/stream-chat-react-native#1773]
Re: https://getstream.io/chat/docs/sdk/reactnative/basics/offline-support/ 

QuickSqliteClient.resetDB();
chatClient.disconnectUser();

This causes a crash - currently on 5.0.1 of react-native-quick-sqlite.

**Comment by vishalnarkhede** [comment]
@billnbell do you have a crash report?

**Comment by 99xtal** [comment]
Code: 

> export const disconnectGetStream = async (getStreamAccessKey: string) => {
  const client = StreamChat.getInstance(getStreamAccessKey);
  log.info('----> Disconnecting user from GetStream');
  if (client) {
    QuickSqliteClient.resetDB();
    await client.disconnectUser();
  }
};

Error message and call stack:
>Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read property 'message' of undefined
TypeError: Cannot read property 'message' of undefined
    at anonymous (http://localhost:8081/index.bundle:132553:29)
    at anonymous (http://localhost:8081/index.bundle:132569:29)
    at anonymous (http://localhost:8081/index.bundle:132592:38)
    at anonymous (http://localhost:8081/index.bundle:132637:33)
    at ?anon_0_ (http://localhost:8081/index.bundle:290778:94)
    at next (native)
    at asyncGeneratorStep (http://localhost:8081/index.bundle:21736:26)
    at _next (http://localhost:8081/index.bundle:21755:29)
    at anonymous (http://localhost:8081/index.bundle:21760:14)
    at tryCallTwo (/Users/distiller/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/Users/distiller/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/Users/distiller/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://localhost:8081/index.bundle:21752:25)
    at apply (native)
    at disconnectGetStream (http://localhost:8081/index.bundle:290783:26)
    at ?anon_0_ (http://localhost:8081/index.bundle:455593:99)
    at next (native)
    at asyncGeneratorStep (http://localhost:8081/index.bundle:21736:26)
    at _next (http://localhost:8081/index.bundle:21755:29)
    at anonymous (http://localhost:8081/index.bundle:21760:14)
    at tryCallTwo (/Users/distiller/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/Users/distiller/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/Users/distiller/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://localhost:8081/index.bundle:21752:25)
    at apply (native)
    at handleGSDisconnect (http://localhost:8081/index.bundle:455599:27)
    at ?anon_0_ (http://localhost:8081/index.bundle:455604:33)
    at next (native)
    at asyncGeneratorStep (http://localhost:8081/index.bundle:21736:26)
    at _next (http://localhost:8081/index.bundle:21755:29)
    at anonymous (http://localhost:8081/index.bundle:21760:14)
    at tryCallTwo (/Users/distiller/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/Users/distiller/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/Users/distiller/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://localhost:8081/index.bundle:21752:25)
    at apply (native)
    at handleLogout (http://localhost:8081/index.bundle:455631:27)
    at _performTransitionSideEffects (http://localhost:8081/index.bundle:78006:22)
    at _receiveSignal (http://localhost:8081/index.bundle:77960:45)
    at onResponderRelease (http://localhost:8081/index.bundle:77825:34)
    at apply (native)
    at invokeGuardedCallbackProd (http://localhost:8081/index.bundle:5321:21)
    at apply (native)
    at invokeGuardedCallback (http://localhost:8081/index.bundle:5421:42)
    at apply (native)
    at invokeGuardedCallbackAndCatchFirstError (http://localhost:8081/index.bundle:5425:36)
    at executeDispatch (http://localhost:8081/index.bundle:5492:48)
    at executeDispatchesInOrder (http://localhost:8081/index.bundle:5511:26)
    at executeDispatchesAndRelease (http://localhost:8081/index.bundle:6691:35)
    at executeDispatchesAndReleaseTopLevel (http://localhost:8081/index.bundle:6698:43)
    at forEach (native)
    at forEachAccumulated (http://localhost:8081/index.bundle:5972:22)
    at runEventsInBatch (http://localhost:8081/index.bundle:6710:27)
    at runExtractedPluginEventsInBatch (http://localhost:8081/index.bundle:6776:25)
    at anonymous (http://localhost:8081/index.bundle:6756:42)
    at batchedUpdates$1 (http://localhost:8081/index.bundle:17971:20)
    at batchedUpdates (http://localhost:8081/index.bundle:6678:36)
    at _receiveRootNodeIDEvent (http://localhost:8081/index.bundle:6755:23)
    at receiveTouches (http://localhost:8081/index.bundle:6803:34)
    at apply (native)
    at __callFunction (http://localhost:8081/index.bundle:4835:36)
    at anonymous (http://localhost:8081/index.bundle:4585:31)
    at __guard (http://localhost:8081/index.bundle:4783:15)
    at callFunctionReturnFlushedQueue (http://localhost:8081/index.bundle:4584:21

**Comment by billnbell** [comment]
see above - thanks Joe.

**Comment by vishalnarkhede** [comment]
@billnbell @99xtal I would suggest you to test the app with v4 react-native-quick-sqlite. We haven't yet tested the library with v5 of that package.

**Comment by vishalnarkhede** [comment]
quick-sqlite dependency will be upgraded to v5 soon - https://github.com/GetStream/stream-chat-react-native/issues/1709#issuecomment-1320836232

Please keep an eye on releases :)

**Comment by vishalnarkhede** [comment]
@billnbell This issue has been fixed as part of our next beta release - https://github.com/GetStream/stream-chat-react-native/releases/tag/v5.6.0-beta.0
