### ISSUE TITLE
ERROR in ./node_modules/react-navigation-tabs/src/views/MaterialTopTabBar.js

### ISSUE THREAD

**Issue by billiemead** [GetStream/stream-chat-react-native#222]
```
ERROR in ./node_modules/react-navigation-tabs/src/views/MaterialTopTabBar.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: g:\_ADALO\stream-chat-app\node_modules\react-navigation-tabs\src\views\MaterialTopTabBar.js: Support for the experimental syntax 'flow' isn't currently enabled (8:8):

   6 | import CrossFadeIcon from './CrossFadeIcon';
   7 | 
>  8 | export type TabBarOptions = {
     |        ^
   9 |   activeTintColor?: string,
  10 |   inactiveTintColor?: string,
  11 |   showLabel?: boolean,

Add @babel/preset-flow (https://git.io/JfeDn) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-flow (https://git.io/vb4yb) to the 'plugins' section to enable parsing.
    at Object._raise (g:\_ADALO\stream-chat-app\node_modules\@babel\parser\lib\index.js:746:17)
    at Object.raiseWithData (g:\_ADALO\stream-chat-app\node_modules\@babel\parser\lib\index.js:739:17)
    at Object.expectOnePlugin (g:\_ADALO\stream-chat-app\node_modules\@babel\parser\lib\index.js:8822:18)
    at Object.isExportDefaultSpecifier (g:\_ADALO\stream-chat-app\node_modules\@babel\parser\lib\index.js:12380:16)
    at Object.maybeParseExportDefaultSpecifier (g:\_ADALO\stream-chat-app\node_modules\@babel\parser\lib\index.js:12273:14)
    at Object.parseExport (g:\_ADALO\stream-chat-app\node_modules\@babel\parser\lib\index.js:12226:29)
    at Object.parseStatementContent (g:\_ADALO\stream-chat-app\node_modules\@babel\parser\lib\index.js:11260:27)
    at Object.parseStatement (g:\_ADALO\stream-chat-app\node_modules\@babel\parser\lib\index.js:11156:17)
    at Object.parseBlockOrModuleBlockBody (g:\_ADALO\stream-chat-app\node_modules\@babel\parser\lib\index.js:11731:25)
    at Object.parseBlockBody (g:\_ADALO\stream-chat-app\node_modules\@babel\parser\lib\index.js:11717:10)
 @ ./node_modules/react-navigation-tabs/src/index.js 24:11-47
 @ ./node_modules/react-navigation/src/react-navigation.js
 @ ./src/components/StreamChatApp/index.js
 @ ./index.js
 @ ./dist/input/editor.js
i ｢wdm｣: Failed to compile.
```

I did try to add @babel/preset-flow  to the 'presets' section of the Babel config, but error persists.

**Comment by vishalnarkhede** [comment]
Hey @billiemead , can you please try giving more details. Just the error gives me no information about what exactly the issue is!!

**Comment by virdesai** [comment]
closing as this is stale with no info
