### ISSUE TITLE
[🐛] When using with Expo it breaks the web version with "Illegal invocation" error and crashes app

### ISSUE THREAD

**Issue by alexmlong** [GetStream/stream-chat-react-native#2491]
## Issue

When I add ContentProvider to my app it causes the app to crash when building for web. It works fine for iOS.

```
import { Stack } from "expo-router"
import React from "react"

import { OverlayProvider } from "stream-chat-expo"

export default function RootLayout() {
  return (
    <OverlayProvider>
      <Stack>
        <Stack.Screen name="index" />
      </Stack>
    </OverlayProvider>
  )
}
```
^ This causes the app crash with "Illegal invocation" until I remove the "OverlayProvider"

Error:
```
TypeError: Illegal invocation
    at Headers.set (/Users/alexlong/projects/tabs-expo-app/node_modules/whatwg-url-without-unicode/lib/URLSearchParams.js:342:17)
    at Proxy.<anonymous> (/Users/alexlong/projects/tabs-expo-app/node_modules/@remix-run/web-fetch/src/headers.js:122:44)
    at convertHeaders (/Users/alexlong/projects/tabs-expo-app/node_modules/@expo/server/src/vendor/http.ts:80:17)
    at convertRequest (/Users/alexlong/projects/tabs-expo-app/node_modules/@expo/server/src/vendor/http.ts:57:14)
    at /Users/alexlong/projects/tabs-expo-app/node_modules/@expo/server/src/vendor/http.ts:34:23
    at call (/Users/alexlong/projects/tabs-expo-app/node_modules/connect/index.js:239:7)
    at next (/Users/alexlong/projects/tabs-expo-app/node_modules/connect/index.js:183:5)
    at middleware (/Users/alexlong/projects/tabs-expo-app/node_modules/@expo/cli/src/start/server/middleware/ExpoMiddleware.ts:62:16)
    at call (/Users/alexlong/projects/tabs-expo-app/node_modules/connect/index.js:239:7)
    at next (/Users/alexlong/projects/tabs-expo-app/node_modules/connect/index.js:183:5)
```

### Steps to reproduce

1. Make a new project with Expo (I used create-expo-app@latest)
2. Wrap your layout with ContentProvider
3. See error

### Expected behavior

I would expect nothing to happen simply from the addition of the ContentProvider.

### Customization

<details><summary>Click To Expand</summary>
<p>

```typescript jsx
# N/A
```
</p>
</details>

### Offline support

- [ ] I have enabled offline support.
- [ ] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

## Environment

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "name": "tabs-expo-app",
  "main": "expo-router/entry",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "test": "jest --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "^14.0.0",
    "@react-navigation/native": "^6.0.2",
    "expo": "~50.0.14",
    "expo-font": "~11.10.3",
    "expo-linking": "~6.2.2",
    "expo-router": "~3.4.8",
    "expo-splash-screen": "~0.26.4",
    "expo-status-bar": "~1.11.1",
    "expo-system-ui": "~2.9.3",
    "expo-web-browser": "~12.8.2",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.73.6",
    "react-native-safe-area-context": "4.8.2",
    "react-native-screens": "~3.29.0",
    "react-native-web": "~0.19.6",
    "stream-chat-expo": "^5.27.1"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.2.45",
    "jest": "^29.2.1",
    "jest-expo": "~50.0.4",
    "react-test-renderer": "18.2.0",
    "typescript": "^5.1.3"
  },
  "private": true
}

```

**`react-native info` output:**

```
info Fetching system and libraries information...
System:
  OS: macOS 14.2.1
  CPU: (12) arm64 Apple M2 Pro
  Memory: 72.77 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.10.0
    path: ~/.nvm/versions/node/v20.10.0/bin/node
  Yarn:
    version: 1.22.22
    path: ~/.nvm/versions/node/v20.10.0/bin/yarn
  npm:
    version: 10.2.3
    path: ~/.nvm/versions/node/v20.10.0/bin/npm
  Watchman:
    version: 2024.04.08.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10406996
  Xcode:
    version: 15.1/15C65
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.6
    wanted: 0.73.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: true
  newArchEnabled: false

info React Native v0.73.7 is now available (your project is running on v0.73.6).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.73.7
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.73.7
info For more info, check out "https://reactnative.dev/docs/upgrading?os=macos".
```

- **Platform that you're experiencing the issue on**:
    - [ ] iOS
    - [ ] Android
    - [ ] **iOS** but have not tested behavior on Android
    - [ ] **Android** but have not tested behavior on iOS
    - [ ] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    - `e.g. 5.4.3`
- Device/Emulator info:
  - [ ] I am using a physical device
  - OS version: `e.g. Android 10`
  - Device/Emulator: `e.g. iPhone 11`

</p>
</details>

### Screenshots

<details><summary>Click To Expand</summary>
<p>

</p>
</details>

---

**Comment by alexmlong** [comment]
Maybe stream chat just doesn't work with the web version?

**Comment by khushal87** [comment]
Hey @alexmlong, we do not support the web as a platform in our React Native SDK as of now so this error is expected. More info [here](https://getstream.io/chat/docs/sdk/reactnative/#platform-compatibilities).
