### ISSUE TITLE
Issue with react native animated

### ISSUE THREAD

**Issue by tuneerclixlogix** [GetStream/stream-chat-react-native#583]
Which version of react-native-animated has to be used 1.13.2 or the 2.0.1 ?
i am facing issues with the both the versions
First I was using version 1.13.2 and i was facing the following issue with the <MessageList>
![image](https://user-images.githubusercontent.com/72122766/112986422-1a1e4e80-917f-11eb-96c7-516fb6b88bba.png)

Then i upgraded the react-native-animated to 2.0.1 and did the babel changes. 
Then i am facing this 
![image](https://user-images.githubusercontent.com/72122766/112985185-7d0ee600-917d-11eb-9f77-feceeceefa51.png)

**Comment by vishalnarkhede** [comment]
@tuneerclixlogix is this android or iOS? Also did you follow the setup steps mentioned here?

https://docs.swmansion.com/react-native-reanimated/docs/installation/#android

**Comment by tuneerclixlogix** [comment]
This is for the iOS, yes i upgraded the package then updated the pods and also added

**Comment by tuneerclixlogix** [comment]
@vishalnarkhede I tried in android too its giving following error
![image](https://user-images.githubusercontent.com/72122766/113003682-979e8a80-9190-11eb-8a76-dd5558986223.png)
![image](https://user-images.githubusercontent.com/72122766/113003752-a71dd380-9190-11eb-894d-ab6dd07b707f.png)

**Comment by tuneerclixlogix** [comment]
While displaying <MessageInput /> I get this
![image](https://user-images.githubusercontent.com/72122766/113007066-8440ee80-9193-11eb-862f-4619e948f790.png)
This is the way am using it 
<Chat client={client} style={theme}>
  <Channel
    channel={channel}
    keyboardVerticalOffset={headerHeight}
    
  >
    <MessageList
      TypingIndicator={TypingComponent}
      LoadingIndicator={MessageLoader}
      setImages={(images) => console.log('images', images)}
    />
    <MessageInput />
  </Channel>
</Chat>
@vishalnarkhede If its possible can you share an example with version 3.2.0

**Comment by vishalnarkhede** [comment]
@tuneerclixlogix we have following examples

- https://github.com/GetStream/stream-chat-react-native/tree/master/examples
- https://github.com/GetStream/stream-chat-react-native/wiki/Cookbook-v3.0#custom-components

Whats the `setImages` call for in your code?

**Comment by nhannah** [comment]
Hi @tuneerclixlogix If you have the OverlayProvider properly setup around the app https://github.com/GetStream/stream-chat-react-native/wiki/Cookbook-v3.0#OverlayProvider and restart (I suggest resetting the cache to be sure), then this issue should not occur.

**Comment by tuneerclixlogix** [comment]
Thanks @nhannah @vishalnarkhede , the errors were because i was missing the OverlayProvider.
Now when i select the image from the default MessageInput i get the following error 
2021-03-31 12:07:03.791 11496-11496/com.app.trueflutterdating E/unknown:ReactNative: Exception in native call
    com.facebook.react.uimanager.IllegalViewOperationException: stack size 8192KB
        at com.facebook.react.ReactRootView.handleException(ReactRootView.java:615)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:711)
        at android.view.View.draw(View.java:23785)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.draw(View.java:23785)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.draw(View.java:23785)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.draw(View.java:23785)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
        at com.facebook.react.ReactRootView.dispatchDraw(ReactRootView.java:226)
        at android.view.View.draw(View.java:23785)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
        at android.view.View.draw(View.java:23918)
        at eightbitlab.com.blurview.BlockingBlurController.updateBlur(BlockingBlurController.java:149)
        at eightbitlab.com.blurview.BlockingBlurController.draw(BlockingBlurController.java:225)
        at eightbitlab.com.blurview.BlurView.draw(BlurView.java:51)
        at android.view.View.draw(View.java:23787)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.draw(View.java:23785)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.draw(View.java:23918)
        at android.view.View.draw(View.java:23787)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.draw(View.java:23785)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.draw(View.java:23785)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.draw(View.java:23785)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.draw(View.java:23918)
        at android.view.View.draw(View.java:23787)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.draw(View.java:23785)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
        at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
        at android.view.View.draw(View.java:23785)
        at android.view.ViewGroup.drawChild(ViewGroup.java:5336)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5093)
        
 Also, if i customize the MessageInput then which methods to be called to open image picker ? with version 2.1.2 i was calling the _pickImage method, so whats the substitute of that in version 3.2.0

**Comment by tuneerclixlogix** [comment]
Its not happening on image uploading but happening anytime while texting or image uploading. And working fine on iOS now. 
I will create another issue with complete logs.
